CREATE TABLE receita (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    chef VARCHAR(100),
    difficulty VARCHAR(50) NOT NULL,
    time VARCHAR(50) NOT NULL,
    rating DECIMAL(3,1),
    image VARCHAR(255)

);


ALTER TABLE receita MODIFY COLUMN ingredients TEXT NULL;

ALTER TABLE receita MODIFY COLUMN instructions TEXT; -- ou VARCHAR(5000) etc

ALTER TABLE receita
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;